site_name: Generativemasks Docs
docs_dir: "docs"
theme:
  name: material
  language: en
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  # タブ表示を有効.
  features:
    - navigation.tabs
    - navigation.tabs.sticky
copyright: "Copyright © TART K.K. 2021"
nav:
  - HOME: index.md
  - Artist: artist.md
  - Team: team.md
  - FAQ: faq.md
